(setq count-number 0)
(defun count-number-insert-increase ()
  (interactive)
  (insert (number-to-string count-number))
  (count-number-increase))
(defun count-number-increase ()
  (interactive)
  (setq count-number (+ 1 count-number)))
(defun count-number-reset ()
  (interactive)
  (message "count-number has been reset to 0")
  (setq count-number 0))
(provide 'genmacros)
